version: "3"
services:
  neo4j:
    container_name: db_skill_graph
    image: neo4j:latest
    networks: ["neo4j_skill_graph"]
    volumes:
      - ./db/data:/data
      - ./db/plugins:/plugins
      - ./db/import:/import
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/test
    restart: unless-stopped

  api:
    container_name: api_skill_graph
    build: ./api
    networks: ["neo4j_skill_graph"]
    command: uvicorn api.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev
      - TESTING=0
    links:
      - neo4j:neo4j
    depends_on:
      - neo4j

networks: { neo4j_skill_graph: {} }